### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [mmaemura/tiktok#1]
Hi Kelly, Emma, and Matthew, 

This looks like a very interesting idea! If I understand correctly, one of the main outputs is going to be a sentiment score for popular TikToks collected over a given weekly period. You'll then explain how you computed the sentiment scores, and visualize the results. 

Overall, I do like this direction. That said, I think "data analysis in a notebook / blog post" is not _quite_ as ambitious as I'd like to see for a group of three people, unless you also do something surprisingly complex involving the sentiment analysis task or the visualizations. With that in mind, I'd like to suggest a slightly modified goal: 

Your deliverable would be a webapp in which the user can interactively select different subsets of TikToks (e.g. by time period), which you've pre-collected and stored in a database. This would allow you to demonstrate some web development skills, and would also allow you to do potentially more complex things regarding interactive data analysis. It would be especially cool if the user could actually query the API through the app, so that they could get *current* trending TikToks. 

You don't actually have to do this exact thing, but I would like you to either (a) propose a slightly more complex version of your project or (b) go into some more detail on how what you've currently planned out is going to push your skills. 

Additionally, I'd like you to be somewhat more concrete about your resources. Can you supply a link to the TikTok API that you plan to use? Can you enumerate the Python packages you expect to use (e.g. for transcription), or at least a few candidates? Giving me details like this makes it clear that you have all the resources you need and that your plan is feasible. 

Once you've thought about this a bit and made your revisions, just reply to this issue and let me know. I'll check it out and assess credit for the assignment. 

I'm excited to see what you create!

**Comment by kellyc3** [comment]
Hi Professor Chodrow! We have altered the initial proposal and have decided to create a web app that is able to perform sentiment analysis on trending TikToks in real time. This will require additional model- and web app-building skills to extend our learning and ambition for this project.

**Comment by PhilChodrow** [comment]
Looks good, thanks for your thoughtful revisions! You have received credit for the project proposal.
